name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validasi compose
        run: docker compose config -q
      - name: Cek sintaks Python
        run: python -m py_compile services/api/main.py services/worker-doc/main.py
      - name: Build semua image
        run: docker compose build
